/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sip;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Azura
 */
public class Pelanggan extends JInternalFrame implements ActionListener, FocusListener {

    /**
     * Creates new form NewJInternalFrame
     */
//    public NewJInternalFrame() {
//        initComponents();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private JPanel jpPelanggan = new JPanel();

    private JLabel lblKode_Pelanggan = new JLabel("Kode Pelanggan:"),
            lblNama = new JLabel("Nama:"),
            lblAlamat = new JLabel("Alamat:"),
            lblKota = new JLabel("Kota:"),
            lblProvinsi = new JLabel("Provinsi:"),
            lblKodePos = new JLabel("Kode Pos:"),
            lblJK = new JLabel("Jenis Kelamin :"),
            lblTelepon = new JLabel("Telepon :"),
            lblHP = new JLabel("HP :"),
            lblAgama = new JLabel("Agama:");

    private JTextField txtKode_Pelanggan = new JTextField(),
            txtNama = new JTextField(),
            txtKode_Pos = new JTextField(),
            txtTelepon = new JTextField(),
            txtHP = new JTextField();

    private JTextArea txaAlamat = new JTextArea();

    private String[] arrAgama = {"Islam", "Kristen", "Katolik", "Hindu", "Budha"};

    private JComboBox cboKota = new JComboBox(),
            cboProvinsi = new JComboBox(),
            cboAgama = new JComboBox(arrAgama);

    private ButtonGroup bgJK = new ButtonGroup();

    private JRadioButton rbPria = new JRadioButton("Pria", true),
            rbWanita = new JRadioButton("Wanita", false);

    private JButton btnTambah = new JButton(new ImageIcon("")),
            btnUbah = new JButton(new ImageIcon("")),
            btnHapus = new JButton(new ImageIcon("")),
            btnBersih = new JButton(new ImageIcon(""));

    public Pelanggan() {
        //super(Judul, Ukuran, Close, Maksimum, Minimum)
        super("Data Entri Master Pelanggan", false, true, false, true);
        setSize(580, 380);

        jpPelanggan.setLayout(null);

        //mengatur objek text are
        txaAlamat.setLineWrap(true);
        txaAlamat.setWrapStyleWord(true);
        JScrollPane scrollPane = new JScrollPane(txaAlamat,
                ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
                ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        bgJK.add(rbPria);
        bgJK.add(rbWanita);

        //mengatur letak objek pada container
        lblKode_Pelanggan.setBounds(15, 20, 100, 25);
        lblNama.setBounds(15, 50, 100, 25);
        lblAlamat.setBounds(15, 80, 100, 25);
        lblKota.setBounds(125, 145, 100, 25);
        lblProvinsi.setBounds(125, 175, 100, 25);
        lblKodePos.setBounds(125, 250, 100, 25);
        lblJK.setBounds(15, 235, 100, 25);
        lblTelepon.setBounds(15, 265, 100, 25);
        lblHP.setBounds(270, 265, 100, 25);
        lblAgama.setBounds(15, 295, 100, 25);

        txtKode_Pelanggan.setBounds(125, 20, 100, 25);
        txtNama.setBounds(125, 50, 320, 25);
        scrollPane.setBounds(125, 80, 320, 60);
        cboKota.setBounds(200, 145, 150, 25);
        cboProvinsi.setBounds(200, 175, 150, 25);
        txtKode_Pos.setBounds(200, 205, 80, 25);
        rbPria.setBounds(125, 235, 100, 25);
        rbWanita.setBounds(230, 235, 100, 25);
        txtTelepon.setBounds(125, 265, 130, 25);
        txtHP.setBounds(300, 265, 145, 25);
        cboAgama.setBounds(125, 295, 130, 25);

        //mengatur objek tombol aktif dan tidak
        btnTambah.setBounds(465, 175, 85, 25);
        btnUbah.setBounds(465, 205, 85, 25);
        btnHapus.setBounds(WIDTH, WIDTH, WIDTH, WIDTH);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void focusGained(FocusEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void focusLost(FocusEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
